# Generated by Django 3.0.5 on 2020-04-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('hash', models.TextField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='img/')),
            ],
        ),
    ]
