# Generated by Django 3.0.5 on 2020-04-10 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadImage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='date_at',
            field=models.DateField(default=datetime.datetime(2020, 4, 10, 6, 52, 50, 439029)),
        ),
    ]
