# Generated by Django 3.0.5 on 2020-04-10 09:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uploadImage', '0002_imagemodel_date_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='date_at',
            field=models.DateField(default=datetime.datetime(2020, 4, 10, 9, 38, 14, 338418, tzinfo=utc)),
        ),
    ]
