# Generated by Django 3.0.5 on 2020-04-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadImage', '0003_auto_20200410_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='date_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
