# Generated by Django 3.0.5 on 2020-04-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadImage', '0005_auto_20200410_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
