# Generated by Django 3.0.5 on 2020-04-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadImage', '0006_auto_20200410_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
